02-Jun-23 22:38:44 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:44 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:44 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:44 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:44 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:44 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:44 - root - INFO - Using queue client rabbitmq - queue_client.py - 162 - get_client
02-Jun-23 22:38:44 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:44 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:44 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:44 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:44 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:44 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 22:38:44 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 57599, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 22:38:44 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 22:38:44 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 22:38:44 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 22:38:44 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57600), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 22:38:44 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x112aa1940>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x112aa1940> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 22:38:45 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x112aa1940> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 22:38:45 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x112aa1940> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 22:38:45 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x112aa1940> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 22:38:45 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 22:38:45 - root - INFO - Connected to queue todo_queue at localhost:5672 - queue_client.py - 90 - connect
02-Jun-23 22:38:45 - root - WARNING - Warning: Optional environment variable FLOCK_MANAGEMENT_STORE_TYPE is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:45 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:45 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:45 - root - INFO - Waiting for messages. on queue todo_queue - queue_client.py - 135 - consume
02-Jun-23 22:42:17 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:17 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:17 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:17 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:17 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:17 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:17 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:17 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:17 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:17 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:17 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:17 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:17 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:17 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:17 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:17 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:17 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:17 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:17 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:17 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:17 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:17 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:17 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:17 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:17 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:17 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:17 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:17 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:17 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:17 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:41 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:41 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:41 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:41 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:41 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:41 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:47 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:47 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:47 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:42:47 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:42:47 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:42:47 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:43:09 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:43:09 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:43:09 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:43:09 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:43:09 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:43:09 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - INFO - Using queue client rabbitmq - queue_client.py - 161 - get_client
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 22:48:42 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 57796, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 22:48:42 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 22:48:42 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 22:48:42 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 22:48:42 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57797), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 22:48:42 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105a1c880>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105a1c880> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 22:48:42 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105a1c880> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 22:48:42 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105a1c880> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 22:48:42 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105a1c880> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 22:48:42 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 22:48:42 - root - INFO - Connected to queue todo_queue at localhost:5672 - queue_client.py - 90 - connect
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable FLOCK_MANAGEMENT_STORE_TYPE is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:48:42 - root - INFO - Waiting for messages. on queue todo_queue - queue_client.py - 134 - consume
02-Jun-23 22:48:42 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:48:42 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:48:42 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:49:01 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:49:01 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:49:01 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:49:04 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:49:04 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:49:04 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:49:42 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:49:42 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:49:42 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:49:48 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:49:48 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:49:48 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:55:12 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:55:12 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:55:12 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:55:42 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:55:42 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:55:42 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:56:39 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:56:39 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:56:39 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 22:56:44 - root - INFO - Received message - task_manager.py - 22 - callback
02-Jun-23 22:56:44 - root - INFO - Labeling message - task_manager.py - 35 - label
02-Jun-23 22:56:44 - root - INFO - Formatting message - task_manager.py - 39 - _format
02-Jun-23 23:36:55 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:36:55 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:36:55 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:36:55 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:36:55 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:36:55 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:36:55 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:36:55 - root - INFO - Using queue client rabbitmq - queue_client.py - 146 - get_client
02-Jun-23 23:36:55 - root - ERROR - Must specify queue name - queue_client.py - 51 - __init__
02-Jun-23 23:39:23 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:39:23 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:39:23 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:39:23 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:39:23 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:39:23 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:39:23 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:39:23 - root - INFO - Using queue client rabbitmq - queue_client.py - 146 - get_client
02-Jun-23 23:39:23 - root - ERROR - Must specify queue name - queue_client.py - 51 - __init__
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:47:05 - root - INFO - Using queue client rabbitmq - queue_client.py - 146 - get_client
02-Jun-23 23:47:05 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 23:47:05 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 58842, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 23:47:05 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 23:47:05 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 23:47:05 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 23:47:05 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 58843), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 23:47:05 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x106cdb7f0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x106cdb7f0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 23:47:05 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x106cdb7f0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 23:47:05 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x106cdb7f0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 23:47:05 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x106cdb7f0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 23:47:05 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 23:47:05 - root - INFO - Connected to queue flock_queue at localhost:5672 - queue_client.py - 73 - connect
02-Jun-23 23:47:05 - root - WARNING - Warning: Optional environment variable FLOCK_MANAGEMENT_STORE_TYPE is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:48:17 - root - INFO - Using queue client rabbitmq - queue_client.py - 146 - get_client
02-Jun-23 23:48:22 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 23:48:22 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 58871, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 23:48:22 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 23:48:22 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 23:48:22 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 23:48:22 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 58872), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 23:48:22 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10671fca0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10671fca0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 23:48:22 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10671fca0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 23:48:22 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10671fca0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 23:48:22 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10671fca0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 23:48:22 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 23:48:28 - root - INFO - Connected to queue flock_queue at localhost:5672 - queue_client.py - 73 - connect
02-Jun-23 23:48:36 - root - WARNING - Warning: Optional environment variable FLOCK_MANAGEMENT_STORE_TYPE is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:49:52 - root - INFO - Using queue client rabbitmq - queue_client.py - 146 - get_client
02-Jun-23 23:49:57 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 23:49:57 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 58894, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 23:49:57 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 23:49:57 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 23:49:57 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 23:49:57 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 58895), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 23:49:57 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10595be50>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10595be50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 23:49:57 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10595be50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 23:49:57 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10595be50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 23:49:57 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10595be50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 23:49:57 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 23:49:57 - root - INFO - Connected to queue flock_queue at localhost:5672 - queue_client.py - 73 - connect
02-Jun-23 23:49:57 - root - WARNING - Warning: Optional environment variable FLOCK_MANAGEMENT_STORE_TYPE is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:20 - root - INFO - Using queue client rabbitmq - queue_client.py - 146 - get_client
02-Jun-23 23:50:20 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 23:50:20 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 58916, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 23:50:20 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 23:50:20 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 23:50:20 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 23:50:20 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 58917), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 23:50:20 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1078a28e0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1078a28e0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 23:50:20 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1078a28e0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 23:50:20 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1078a28e0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 23:50:20 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1078a28e0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 23:50:20 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 23:50:20 - root - INFO - Connected to queue flock_queue at localhost:5672 - queue_client.py - 73 - connect
02-Jun-23 23:50:20 - root - WARNING - Warning: Optional environment variable FLOCK_MANAGEMENT_STORE_TYPE is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:50:27 - root - INFO - Waiting for messages. on queue flock_queue - queue_client.py - 119 - consume
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:00 - root - INFO - Using queue client rabbitmq - queue_client.py - 145 - get_client
02-Jun-23 23:55:00 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 23:55:00 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 59048, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 23:55:00 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 23:55:00 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 23:55:00 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 23:55:00 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 59049), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 23:55:00 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10796ac40>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10796ac40> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 23:55:00 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10796ac40> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 23:55:00 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10796ac40> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 23:55:00 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10796ac40> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 23:55:00 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 23:55:00 - root - INFO - Connected to queue flock_queue at localhost:5672 - queue_client.py - 72 - connect
02-Jun-23 23:55:00 - root - WARNING - Warning: Optional environment variable FLOCK_MANAGEMENT_STORE_TYPE is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:55:09 - root - INFO - Waiting for messages. on queue flock_queue - queue_client.py - 118 - consume
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - INFO - Using queue client rabbitmq - queue_client.py - 145 - get_client
02-Jun-23 23:56:19 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 23:56:19 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 59086, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 23:56:19 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 23:56:19 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 23:56:19 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 23:56:19 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 59087), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 23:56:19 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105bf48b0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105bf48b0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 23:56:19 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105bf48b0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 23:56:19 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105bf48b0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 23:56:19 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105bf48b0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 23:56:19 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 23:56:19 - root - INFO - Connected to queue flock_queue at localhost:5672 - queue_client.py - 72 - connect
02-Jun-23 23:56:19 - root - WARNING - Warning: Optional environment variable FLOCK_MANAGEMENT_STORE_TYPE is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:56:19 - root - INFO - Waiting for messages. on queue flock_queue - queue_client.py - 118 - consume
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:58:46 - root - INFO - Using queue client rabbitmq - queue_client.py - 145 - get_client
02-Jun-23 23:58:46 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 23:58:46 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 59125, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 23:58:46 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 23:58:46 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 23:58:46 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 23:58:46 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 59126), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 23:58:46 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104430b80>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104430b80> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 23:58:46 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104430b80> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 23:58:46 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104430b80> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 23:58:46 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104430b80> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 23:58:46 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 23:58:46 - root - INFO - Connected to queue flock_queue at localhost:5672 - queue_client.py - 72 - connect
02-Jun-23 23:58:46 - root - WARNING - Warning: Optional environment variable FLOCK_MANAGEMENT_STORE_TYPE is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:47 - root - INFO - Using queue client rabbitmq - queue_client.py - 145 - get_client
03-Jun-23 00:00:47 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
03-Jun-23 00:00:47 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 59173, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
03-Jun-23 00:00:47 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
03-Jun-23 00:00:47 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
03-Jun-23 00:00:47 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
03-Jun-23 00:00:47 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 59174), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
03-Jun-23 00:00:47 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1087e3bb0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1087e3bb0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
03-Jun-23 00:00:47 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1087e3bb0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
03-Jun-23 00:00:47 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1087e3bb0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
03-Jun-23 00:00:47 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1087e3bb0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
03-Jun-23 00:00:47 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
03-Jun-23 00:00:47 - root - INFO - Connected to queue todo_tickets at localhost:5672 - queue_client.py - 72 - connect
03-Jun-23 00:00:47 - root - WARNING - Warning: Optional environment variable FLOCK_MANAGEMENT_STORE_TYPE is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_DB_NAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_COLLECTION_NAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable MANAGEMENT_STORE_HOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:56 - root - INFO - Using queue client rabbitmq - queue_client.py - 145 - get_client
03-Jun-23 00:00:56 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
03-Jun-23 00:00:56 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 59200, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
03-Jun-23 00:00:56 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
03-Jun-23 00:00:56 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
03-Jun-23 00:00:56 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
03-Jun-23 00:00:56 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 59201), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
03-Jun-23 00:00:56 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1042c4910>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1042c4910> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
03-Jun-23 00:00:56 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1042c4910> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
03-Jun-23 00:00:56 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1042c4910> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
03-Jun-23 00:00:56 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1042c4910> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
03-Jun-23 00:00:56 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
03-Jun-23 00:00:56 - root - INFO - Connected to queue todo_tickets at localhost:5672 - queue_client.py - 72 - connect
03-Jun-23 00:00:56 - root - WARNING - Warning: Optional environment variable FLOCK_MANAGEMENT_STORE_TYPE is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:59 - root - INFO - Waiting for messages. on queue todo_tickets - queue_client.py - 118 - consume
03-Jun-23 00:01:49 - root - INFO - Received message - task_manager.py - 22 - callback
03-Jun-23 00:01:49 - root - INFO - Saved ticket: 64765103e674abbe18fb9e8c - mongo.py - 74 - save_ticket
03-Jun-23 00:01:49 - root - INFO - Received message - task_manager.py - 22 - callback
03-Jun-23 00:02:08 - root - INFO - Received message - task_manager.py - 22 - callback
03-Jun-23 00:02:08 - root - INFO - Received message - task_manager.py - 22 - callback
03-Jun-23 00:02:13 - root - INFO - Received message - task_manager.py - 22 - callback
03-Jun-23 00:02:13 - root - INFO - Received message - task_manager.py - 22 - callback
